use_frameworks!

target 'JKSwiftTabBarController_Example' do
  # TabBarController
  pod 'JKSwiftTabBarController', :path => '../'
  # 基本的扩展库
  pod 'JKSwiftExtension'
  # 网络请求
  pod 'Alamofire'
  # 解压Zip包
  pod 'ZipArchive'
  target 'JKSwiftTabBarController_Tests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
    end
  end
end
